version: "3.6"

services:

  traefik:
    image: traefik:2.8
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --api.insecure=true --providers.docker.swarmmode --log.level=debug
    deploy:
      placement:
        constraints:
          - node.role == manager

  mom:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 5s

  db:
    image: mongo:4.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.runCommand(\"ping\").ok'", "localhost:27017/personnes", "--quiet"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 1s

  ged:
    image: nuxeo:10.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 20s
    deploy:
      labels:
        - "traefik.http.routers.ged.rule=Host(`dockereni.francecentral.cloudapp.azure.com`) && PathPrefix(`/nuxeo/atom/cmis`)"
        - "traefik.http.services.ged.loadbalancer.server.port=8080"

  recep:
    image: jpgouigoux/recepteurmessages:1.4
    build:
      context: .
      dockerfile: RecepteurMessages/Dockerfile
      args:
        - MAXINDEX_XKCD=50
    environment:
      - Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - URLBaseServiceAPI=https://api
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --GED__URLAtomPub=http://ged:8080/nuxeo/atom/cmis
      - --GED__ServiceAccountName=Administrator
      - --GED__ServiceAccountPassword=Administrator
      - --GED__ModeleURLExpositionDirecteDocuments=http://dockereni.francecentral.cloudapp.azure.com/nuxeo/atom/cmis/default/content/{nomFichier}?id={idDoc}
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
    secrets:
      - pwdcertifclient
      - certifclient
    stdin_open: true
    tty: true
    deploy:
      replicas: 3

  api:
    image: jpgouigoux/testoidcblazorwasmapi:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM.API/Dockerfile
    environment:
      - Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
      - --Securite__EmpreinteCertificatClient=41E81F27F42F381B7406129DAAB055802F9A64B9
    secrets:
      - pwdcertifclient
      - certifclient

  server:
    image: jpgouigoux/testoidcblazorwasmserver:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM/Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --OIDC__Authority=https://dockereni.francecentral.cloudapp.azure.com/realms/LivreENI/
      - --OIDC__ClientId=appli-eni
    deploy:
      labels:
        - "traefik.http.routers.server.rule=Host(`dockereni.francecentral.cloudapp.azure.com`)"
        - "traefik.http.services.server.loadbalancer.server.port=80"

secrets:
  pwdcertifclient:
    file: ./MotDePasseCertificatClient.secret
  certifclient:
    file: ./clienttestoidc.pfx
