version: "3.6"

services:

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - caddydata:/data
      - caddyconfig:/config
    deploy:
      placement:
        constraints:
          - node.role == manager

  dbiam:
    image: postgres:14.5
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=KY9CO8sHshzM5YxfLtzL
    volumes:
      - datadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 1s
      retries: 6
      start_period: 5s

  iam:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KEYCLOAK_ADMIN=armoire
      - KEYCLOAK_ADMIN_PASSWORD=vBWtB2PloopC042cszXZ
      - KC_HTTPS_CERTIFICATE_FILE=/run/secrets/crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/run/secrets/key
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dbiam/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=KY9CO8sHshzM5YxfLtzL
    command:
      - start-dev
      - --proxy=edge
      - --hostname=dockereni.francecentral.cloudapp.azure.com:8443
    secrets:
      - crt
      - key
    ports:
      - "8443:8443"

  mom:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 5s

  db:
    image: mongo:4.4
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.runCommand(\"ping\").ok'", "localhost:27017/personnes", "--quiet"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 1s

  ged:
    image: nuxeo:10.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 20s

  recep:
    image: jpgouigoux/recepteurmessages:1.4
    build:
      context: .
      dockerfile: RecepteurMessages/Dockerfile
      args:
        - MAXINDEX_XKCD=50
    environment:
      - Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - URLBaseServiceAPI=https://api
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --GED__URLAtomPub=http://ged:8080/nuxeo/atom/cmis
      - --GED__ServiceAccountName=Administrator
      - --GED__ServiceAccountPassword=Administrator
      - --GED__ModeleURLExpositionDirecteDocuments=https://dockereni.francecentral.cloudapp.azure.com/nuxeo/atom/cmis/default/content/{nomFichier}?id={idDoc}
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
    secrets:
      - pwdcertifclient
      - certifclient
    stdin_open: true
    tty: true
    deploy:
      replicas: 3

  api:
    image: jpgouigoux/testoidcblazorwasmapi:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM.API/Dockerfile
    environment:
      - Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
      - --Securite__EmpreinteCertificatClient=41E81F27F42F381B7406129DAAB055802F9A64B9
    secrets:
      - pwdcertifclient
      - certifclient

  server:
    image: jpgouigoux/testoidcblazorwasmserver:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM/Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --OIDC__Authority=https://dockereni.francecentral.cloudapp.azure.com:8443/realms/LivreENI/
      - --OIDC__ClientId=appli-eni
    ports:
      - "5000:5000"

volumes:
  datadb:
    driver: local
  caddydata:
  caddyconfig:

secrets:
  pwdcertifclient:
    file: ./MotDePasseCertificatClient.secret
  certifclient:
    file: ./clienttestoidc.pfx
  crt:
    file: /home/azureuser/server.crt.pem
  key:
    file: /home/azureuser/server.key.pem
