services:

  caddy:
    image: caddy:2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - caddydata:/data
      - caddyconfig:/config
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: always

  dbiam:
    image: postgres:17.6
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=KY9CO8sHshzM5YxfLtzL
    volumes:
      - datadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 1s
      retries: 6
      start_period: 5s
    restart: always

  iam:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      - KEYCLOAK_ADMIN=armoire
      - KEYCLOAK_ADMIN_PASSWORD=vBWtB2PloopC042cszXZ
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dbiam/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=KY9CO8sHshzM5YxfLtzL
    command:
      - start-dev
      - --proxy-headers=xforwarded
      - --hostname=https://dockereni.francecentral.cloudapp.azure.com/iam/
      - --hostname-backchannel-dynamic=false
      - --proxy-trusted-addresses=0.0.0.0/0
    ports:
      - "0.0.0.0:8080:8080"
    restart: always

  mom:
    image: rabbitmq:4.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 5s
    restart: always

  db:
    image: mongo:8.0
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.runCommand(\"ping\").ok'", "localhost:27017/personnes", "--quiet"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 1s
    ports:
      - "27017:27017"
    restart: always

  ged:
    image: math56890/lightweightcmis:0.5
    ports:
      - "8088:8080"
    restart: always

  recep:
    image: jpgouigoux/recepteurmessages:1.4
    build:
      context: .
      dockerfile: RecepteurMessages/Dockerfile
      args:
        - MAXINDEX_XKCD=50
    environment:
      - URLBaseServiceAPI=http://api
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --GED__URLBrowser=http://ged:8080/lightweightcmis/browser/
      - --GED__ServiceAccountName=admin
      - --GED__ServiceAccountPassword=admin
      - --GED__ModeleURLExpositionDirecteDocuments=https://dockereni.francecentral.cloudapp.azure.com/lightweightcmis/browser/default/root/?cmisselector=content&objectId={idDoc}
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
      - --Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - --XKCD__TemplateURLAPI=https://xkcd.com/{indexImage}/info.0.json
    secrets:
      - pwdcertifclient
      - certifclient
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
    restart: always

  api:
    image: jpgouigoux/testoidcblazorwasmapi:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM.API/Dockerfile
    environment:
      - Securite__CheminFichierCertificatClient=/run/secrets/certifclient
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --Securite__FichierMotDePasseCertificatClient=/run/secrets/pwdcertifclient
      - --Securite__EmpreinteCertificatClient=FDBE54F78826D8EB51F3617C5E3C7A7DCFAF722C
    secrets:
      - pwdcertifclient
      - certifclient
    restart: always

  # Pattern BFF
  server:
    image: jpgouigoux/testoidcblazorwasmserver:1.4
    build:
      context: .
      dockerfile: TestOIDCBlazorWASM/Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command:
      - --RabbitMQ__HoteServeur=mom
      - --RabbitMQ__Utilisateur=rapido
      - --RabbitMQ__MotDePasse=k5rXH6wmBhE2bukfXFsz
      - --RabbitMQ__NomQueueMessagesCreationPersonnes=personnes
      - --PersistanceNoSQL__PersonnesConnectionString=mongodb://db:27017
      - --PersistanceNoSQL__PersonnesDatabaseName=personnes
      - --PersistanceNoSQL__PersonnesCollectionName=personnes
      - --OIDC__Authority=https://dockereni.francecentral.cloudapp.azure.com/iam/realms/LivreENI/
      - --OIDC__ClientId=appli-eni
    ports:
      - "5000:5000"
    restart: always

volumes:
  datadb:
    driver: local
  caddydata:
  caddyconfig:

secrets:
  pwdcertifclient:
    file: ./MotDePasseCertificatClient.secret
  certifclient:
    file: ./clienttestoidc.pfx
